"""
Merge a list of cprofile files generated by running testify --profile tests.
"""

import pstats
import os

def get_filenames(path):
    def is_cprofile(name):
        return name.endswith('.cprofile')
    return filter(is_cprofile, os.listdir(path))

def merge_stats(path):
    filenames = get_filenames(path)
    stats = pstats.Stats(filenames[0])
    for filename in filenames[1:]:
        stats.add(filename)
    return stats


stats = merge_stats('.')
stats.dump_stats('all.cprofile')
stats.sort_stats('cumulative')
stats.print_stats(40)
